%---------------------------------------------------------------------
%---------------------------------------------------------------------
fields_to_keep = { ...
	'filename', ...
	'animal', ...
	'datecode', ...
	'penetration', ...
	'unit', ...
	'other', ...
	'nstim', ...
	'nreps', ...
	'TestType', ...
	'TestName', ...
	'Reps', ...
	'Audio_Signal', ...
	'AcqDuration', ...
	'Audio_Delay', ...
	'Audio_Dur', ...
	'Audio_Level', ...
	'Audio_Ramp', ...
	'Audio_ISI', ...
	'Opto_Enable', ...
	'Opto_Delay', ...
	'Opto_Dur', ...
	'Opto_Amp', ...
	'nChannels', ...
	'ChannelList' ...
	};
	
%---------------------------------------------------------------------
% database path:
%---------------------------------------------------------------------
[data_root_path, tytology_root_path] = optoanalysis_paths;
dbpath = fullfile(data_root_path, 'Analyzed', 'db');

%---------------------------------------------------------------------
% get list of files
%---------------------------------------------------------------------
dList = dir(fullfile(dbpath, '*.mat'));
nfiles = length(dList);
if nfiles == 0
	error('%s: no .dat files found in directory %s', mfilename, dbpath);
end
%---------------------------------------------------------------------
% Load Data and add to table
%---------------------------------------------------------------------
T = table();

for f = 1:nfiles
	datafile = dList(f).name;
	load(fullfile(dbpath, datafile) , 'P', '-MAT');
	tmp = struct2table(P);
	tmp2 = table();
	for k = 1:length(fields_to_keep)
		tmp2.(fields_to_keep{k}) = tmp.(fields_to_keep{k});
	end
	T = [T; tmp2];
end



