%---------------------------------------------------------------------
%---------------------------------------------------------------------
fields_to_keep = { ...
	'filename', ...
	'animal', ...
	'datecode', ...
	'penetration', ...
	'unit', ...
	'other', ...
	'nstim', ...
	'nreps', ...
	'TestType', ...
	'TestName', ...
	'Reps', ...
	'Audio_Signal', ...
	'AcqDuration', ...
	'Audio_Delay', ...
	'Audio_Dur', ...
	'Audio_Level', ...
	'Audio_Ramp', ...
	'Audio_ISI', ...
	'Opto_Enable', ...
	'Opto_Delay', ...
	'Opto_Dur', ...
	'Opto_Amp', ...
	'nChannels', ...
	'ChannelList' ...
	};
	
%---------------------------------------------------------------------
% database path:
%---------------------------------------------------------------------
[data_root_path, tytology_root_path] = optoanalysis_paths;
dbpath = fullfile(data_root_path, 'Analyzed', 'db');

%---------------------------------------------------------------------
% get list of files
%---------------------------------------------------------------------
dList = dir(fullfile(dbpath, '*.mat'));
nfiles = length(dList);
if nfiles == 0
	error('%s: no .dat files found in directory %s', mfilename, dbpath);
end
%---------------------------------------------------------------------
% Load Data and add to table
%---------------------------------------------------------------------
T = table();

Pnet = [];

% first construct net P struct array
for f = 1:nfiles
	tmp = [];
	datafile = dList(f).name;
	load(fullfile(dbpath, datafile) , 'P', '-MAT');
	for r = 1:length(P)
		for p = 1:length(fields_to_keep)
			tmp(r).(fields_to_keep{p}) = P(r).(fields_to_keep{p});
		end
	end
	Pnet = [Pnet tmp];
end
